AdobeReader:
  appBundleIdentifier: 'com.adobe.Reader'
  appCodeRequirement: ''
  appName: 'Adobe Acrobat Reader DC.app'
  dmgFileType: 'pkg'
  downloadFileType: 'dmg'
  downloadType: 'scrape'
  downloadUrl: 'https://ardownload2.adobe.com/pub/adobe/reader/mac/AcrobatDC/%VERSION%/AcroRdrDC_%VERSION%_MUI.dmg'
  pkgChecksum: 'ba80b0709435b7e69e3fdb3576a64f13'
  pkgName: 'AcroRdrDC_[0-9]+_MUI.pkg'
  pkgSigned: true
  scrapeDownloadUrl: 'https://ardownload2.adobe.com/pub/adobe/reader/mac/AcrobatDC/2200120085/AcroRdrDC_2200120085_MUI.dmg'
  scrapeRegex: 'prodesigntools\.com\/ardownload2\/pub\/adobe\/reader\/mac\/AcrobatDC\/([0-9]+)\/AcroRdrDC_[0-9]+_MUI\.dmg'
  scrapeUrl: 'https://prodesigntools.com/acrobat-dc-2022-direct-download-links.html'
AnyDesk:
  appBundleIdentifier: 'com.philandro.anydesk'
  appCodeRequirement: 'identifier "com.philandro.anydesk" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = KU6W3B6JMZ'
  appName: 'AnyDesk.app'
  appVersion: '6.5.0'
  dmgFileType: 'app'
  downloadFileType: 'dmg'
  downloadType: 'direct'
  downloadUrl: 'https://download.anydesk.com/anydesk.dmg'
  pkgChecksum: 'a48b73fec963e6a6089ff60e7077dfa2'
  pkgSigned: false
AppCleaner:
  appBundleIdentifier: 'net.freemacsoft.AppCleaner'
  appCodeRequirement: 'anchor apple generic and identifier "net.freemacsoft.AppCleaner" and (certificate leaf[field.1.2.840.113635.100.6.1.9] /* exists */ or certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = X85ZX835W9)'
  appName: 'AppCleaner.app'
  appVersion: '3.6.3'
  downloadFileType: 'zip'
  downloadType: 'scrape'
  downloadUrl: 'https://freemacsoft.net/downloads/AppCleaner_%VERSION%.zip'
  pkgChecksum: '38ca1b3c6cc4e62d84c9e18ebd1df905'
  pkgSigned: false
  scrapeDownloadUrl: 'https://freemacsoft.net/downloads/AppCleaner_3.6.3.zip'
  scrapeRegex: 'Version\s([0-9.]+)'
  scrapeUrl: 'https://freemacsoft.net/appcleaner/'
  zipFileType: 'app'
Chrome:
  appBundleIdentifier: 'com.google.Chrome'
  appCodeRequirement: '(identifier "com.google.Chrome" or identifier "com.google.Chrome.beta" or identifier "com.google.Chrome.dev" or identifier "com.google.Chrome.canary") and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = EQHXZ8M8AV'
  appName: 'Google Chrome.app'
  appVersion: '99.0.4844.83'
  downloadFileType: 'pkg'
  downloadType: 'direct'
  downloadUrl: 'https://dl.google.com/dl/chrome/mac/universal/stable/gcem/GoogleChrome.pkg'
  pkgChecksum: '3e07b8de4f7c67bcbaa465f286a0b230'
  pkgSigned: true
CitrixWorkspace:
  appBundleIdentifier: 'com.citrix.receiver.nomas'
  appCodeRequirement: 'anchor apple generic and identifier "com.citrix.receiver.nomas" and (certificate leaf[field.1.2.840.113635.100.6.1.9] /* exists */ or certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = S272Y5R93J)'
  appName: 'Citrix Workspace.app'
  appVersion: '22.01.0'
  dmgFileType: 'pkg'
  downloadFileType: 'dmg'
  downloadType: 'scrape'
  downloadUrl: 'https://downloads.citrix.com/%VERSION%'
  pkgChecksum: 'e53c10f8f02bea918acdcc6db91e75e5'
  pkgName: 'Install Citrix Workspace.pkg'
  pkgSigned: true
  scrapeDownloadUrl: 'https://downloads.citrix.com/20341/CitrixWorkspaceApp.dmg?__gda__=exp=1647857999~acl=/*~hmac=8fe63206e32e1de492ea65b22bb72f172a1d200225064db69f596c91b634bec8'
  scrapeRegex: 'downloads\.citrix\.com\/([0-9]+\/CitrixWorkspaceApp\.dmg\?.+hmac\=[0-9a-z]+)'
  scrapeUrl: 'https://www.citrix.com/downloads/workspace-app/mac/workspace-app-for-mac-latest.html'
Cyberduck:
  appBundleIdentifier: 'ch.sudo.cyberduck'
  appCodeRequirement: 'identifier "ch.sudo.cyberduck" and (anchor apple generic and (certificate leaf[field.1.2.840.113635.100.6.1.9] /* exists */ or certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = G69SCX94XU) or certificate root = H"a1fb64aab7a4441436d50b91f310bf8c3dafc22c")'
  appName: 'Cyberduck.app'
  appVersion: '8.2.3'
  downloadFileType: 'zip'
  downloadType: 'scrape'
  downloadUrl: 'https://update.cyberduck.io/Cyberduck-%VERSION%.zip'
  pkgChecksum: 'ac3af4490377259ef134f32768b45905'
  pkgSigned: false
  scrapeDownloadUrl: 'https://update.cyberduck.io/Cyberduck-8.2.3.36880.zip'
  scrapeRegex: 'Cyberduck for macOS\s[<a-z>]+\s[<a-z>]+Cyberduck-([0-9.]+)\.zip'
  scrapeUrl: 'https://cyberduck.io/download/'
  zipFileType: 'app'
Dropbox:
  appName: 'Dropbox.app'
  dmgFileType: 'app'
  downloadFileType: 'dmg'
  downloadType: 'direct'
  downloadUrl: 'https://www.dropbox.com/downloading?full=1&os=mac'
Element:
  appBundleIdentifier: 'im.riot.app'
  appCodeRequirement: 'identifier "im.riot.app" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = "7J4U792NQT"'
  appName: 'Element.app'
  appVersion: '1.10.7'
  dmgFileType: 'app'
  downloadFileType: 'dmg'
  downloadType: 'direct'
  downloadUrl: 'https://packages.riot.im/desktop/install/macos/Element.dmg'
  pkgChecksum: '9ba042bfe02afe78b728993a100b1c8b'
  pkgSigned: false
Firefox-ESR-DE:
  appBundleIdentifier: 'org.mozilla.firefox'
  appCodeRequirement: 'anchor apple generic and certificate leaf[field.1.2.840.113635.100.6.1.9] /* exists */ or anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = "43AQ936H96"'
  appName: 'Firefox.app'
  appVersion: '91.7.1'
  dmgFileType: 'app'
  downloadFileType: 'dmg'
  downloadType: 'direct'
  downloadUrl: 'https://download.mozilla.org/?product=firefox-esr-latest-ssl&os=osx&lang=de'
  pkgChecksum: '423c55d7b5209e3fcfa8083f6f0ff284'
  pkgSigned: false
LibreOffice:
  appBundleIdentifier: 'org.libreoffice.script'
  appCodeRequirement: 'identifier "org.libreoffice.script" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = "7P5S3ZLCN7"'
  appName: 'LibreOffice.app'
  appVersion: '7.2.6.2'
  dmgFileType: 'app'
  downloadFileType: 'dmg'
  downloadType: 'scrape'
  downloadUrl: 'https://download.documentfoundation.org/libreoffice/stable/%VERSION%/mac/x86_64/LibreOffice_%VERSION%_MacOS_x86-64.dmg'
  pkgChecksum: '0d288dc62c791dffb68902a679a82a62'
  pkgSigned: false
  scrapeDownloadUrl: 'https://download.documentfoundation.org/libreoffice/stable/7.2.6/mac/x86_64/LibreOffice_7.2.6_MacOS_x86-64.dmg'
  scrapeRegex: '<span class="dl_version_number">([0-9.]+)<\/span><br \/>\s+<span class="dl_description_text">This version is slightly older'
  scrapeUrl: 'https://www.libreoffice.org/download/download/'
Rectangle:
  appBundleIdentifier: 'com.knollsoft.Rectangle'
  appCodeRequirement: 'anchor apple generic and identifier "com.knollsoft.Rectangle" and (certificate leaf[field.1.2.840.113635.100.6.1.9] /* exists */ or certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = XSYZ3E4B7D)'
  appName: 'Rectangle.app'
  appVersion: '0.53'
  dmgFileType: 'app'
  downloadFileType: 'dmg'
  downloadType: 'scrape'
  downloadUrl: 'https://github.com/rxhanson/Rectangle/releases/download/v%VERSION%/Rectangle%VERSION%.dmg'
  pkgChecksum: '3c4d7f33a150a220152e6aaa7c6191c5'
  pkgSigned: false
  scrapeDownloadUrl: 'https://github.com/rxhanson/Rectangle/releases/download/v0.53/Rectangle0.53.dmg'
  scrapeRegex: 'Rectangle([0-9.]+)\.dmg'
  scrapeUrl: 'https://rectangleapp.com'
TeamViewer:
  appBundleIdentifier: 'com.teamviewer.TeamViewer'
  appCodeRequirement: 'anchor apple generic and identifier "com.teamviewer.TeamViewer" and (certificate leaf[field.1.2.840.113635.100.6.1.9] /* exists */ or certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = H7UGFBUGV6)'
  appName: 'TeamViewer.app'
  appVersion: '15.27.3'
  dmgFileType: 'pkg'
  downloadFileType: 'dmg'
  downloadType: 'direct'
  downloadUrl: 'https://download.teamviewer.com/download/TeamViewer.dmg'
  pkgChecksum: 'a41dd5a436140b488f75a00ec6a7349f'
  pkgName: 'Install TeamViewer.pkg'
  pkgSigned: true
  pkgTarget: '/Applications/.TeamViewer'
TeamViewerQS:
  appBundleIdentifier: 'com.teamviewer.TeamViewerQS'
  appCodeRequirement: 'anchor apple generic and identifier "com.teamviewer.TeamViewerQS" and (certificate leaf[field.1.2.840.113635.100.6.1.9] /* exists */ or certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = H7UGFBUGV6)'
  appName: 'TeamViewerQS.app'
  appVersion: '15.27.3'
  dmgFileType: 'app'
  downloadFileType: 'dmg'
  downloadType: 'direct'
  downloadUrl: 'https://download.teamviewer.com/download/TeamViewerQS.dmg'
  pkgChecksum: 'ae85db04b8c96eb56db1f384c1ffad8c'
  pkgSigned: false
Teams:
  appBundleIdentifier: 'com.microsoft.teams'
  appCodeRequirement: 'identifier "com.microsoft.teams" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = UBF8T346G9'
  appName: 'Microsoft Teams.app'
  appVersion: '1.00.506181'
  downloadFileType: 'pkg'
  downloadType: 'direct'
  downloadUrl: 'https://go.microsoft.com/fwlink/p/?LinkID=869428&clcid=0x407&culture=de-de&country=DE&lm=deeplink&cmpid=directDownloadMac'
  pkgChecksum: '0f12691e2570e053f5f56f315f1b7acb'
  pkgSigned: true
Tunnelblick:
  appBundleIdentifier: 'net.tunnelblick.tunnelblick'
  appCodeRequirement: 'identifier "net.tunnelblick.tunnelblick" and anchor apple generic and certificate leaf[subject.OU] = Z2SG5H3HC8'
  appName: 'Tunnelblick.app'
  appVersion: '3.8.7a (build 5770)'
  dmgFileType: 'app'
  downloadFileType: 'dmg'
  downloadType: 'direct'
  downloadUrl: 'https://tunnelblick.net/release/Latest_Tunnelblick_Stable.dmg'
  pkgChecksum: 'c7f5866a910955dcbc36c4d1b71c7e76'
  pkgSigned: false
Webex_ARM:
  appBundleIdentifier: 'Cisco-Systems.Spark'
  appCodeRequirement: 'identifier "Cisco-Systems.Spark" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = DE8Y96K9QP'
  appName: 'Webex.app'
  appVersion: '42.3.0.21576'
  dmgFileType: 'app'
  downloadFileType: 'dmg'
  downloadType: 'direct'
  downloadUrl: 'https://binaries.webex.com/WebexDesktop-MACOS-Apple-Silicon-Gold/Webex.dmg'
  pkgChecksum: '01cf80464756e4b132cdc2b6a6dc9fc3'
  pkgSigned: false
Webex_Intel:
  appBundleIdentifier: 'Cisco-Systems.Spark'
  appCodeRequirement: 'identifier "Cisco-Systems.Spark" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = DE8Y96K9QP'
  appName: 'Webex.app'
  appVersion: '42.3.0.21576'
  dmgFileType: 'app'
  downloadFileType: 'dmg'
  downloadType: 'direct'
  downloadUrl: 'https://binaries.webex.com/WebexTeamsDesktop-MACOS-Gold/Webex.dmg'
  pkgChecksum: 'dd46a0f312657de89b057a8cedd4f712'
  pkgSigned: false
Zoom:
  appBundleIdentifier: 'us.zoom.xos'
  appCodeRequirement: 'identifier "us.zoom.xos" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = BJ4HAAB9B3'
  appName: 'zoom.us.app'
  appVersion: '5.9.6 (4993)'
  downloadFileType: 'pkg'
  downloadType: 'direct'
  downloadUrl: 'https://zoom.us/client/latest/ZoomInstallerIT.pkg'
  pkgChecksum: 'ca3b3b73b48bff8301a03e49faa59e86'
  pkgSigned: true
alfaview:
  appBundleIdentifier: 'com.alfaview.desktop'
  appCodeRequirement: 'identifier "com.alfaview.desktop" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = AFPV6P844Y'
  appName: 'alfaview.app'
  dmgFileType: 'app'
  downloadFileType: 'dmg'
  downloadType: 'scrape'
  downloadUrl: 'https://assets.alfaview.com/stable/mac/alfaview-mac-production-%VERSION%.dmg'
  scrapeDownloadUrl: 'https://assets.alfaview.com/stable/mac/alfaview-mac-production-8.40.0.dmg'
  scrapeRegex: 'alfaview-mac-production-([0-9.]+)\.dmg'
  scrapeUrl: 'https://assets.alfaview.com/stable/mac/version.info'
calibre:
  appBundleIdentifier: 'net.kovidgoyal.calibre'
  appCodeRequirement: 'identifier "net.kovidgoyal.calibre" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = NTY7FVCEKP'
  appName: 'calibre.app'
  appVersion: '5.39.1'
  dmgFileType: 'app'
  downloadFileType: 'dmg'
  downloadType: 'direct'
  downloadUrl: 'https://calibre-ebook.com/dist/osx'
  pkgChecksum: '2e168e770a91a450cc04b9d0eac8a584'
  pkgSigned: false
